[2025-01-13T00:36:55.547+0000] {processor.py:186} INFO - Started process (PID=1920) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:36:55.548+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:36:55.550+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:36:55.550+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:36:55.571+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:36:55.566+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1, in <module>
    from airflow import dag
ImportError: cannot import name 'dag' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2025-01-13T00:36:55.574+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:36:55.592+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.049 seconds
[2025-01-13T00:37:25.895+0000] {processor.py:186} INFO - Started process (PID=1984) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:37:25.897+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:37:25.899+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:37:25.898+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:37:25.918+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:37:25.913+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1, in <module>
    from airflow import dag
ImportError: cannot import name 'dag' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2025-01-13T00:37:25.920+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:37:25.938+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.048 seconds
[2025-01-13T00:37:55.975+0000] {processor.py:186} INFO - Started process (PID=2049) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:37:55.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:37:55.978+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:37:55.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:37:56.005+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:37:55.999+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1, in <module>
    from airflow import dag
ImportError: cannot import name 'dag' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2025-01-13T00:37:56.007+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:37:56.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.055 seconds
[2025-01-13T00:38:26.925+0000] {processor.py:186} INFO - Started process (PID=2113) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:38:26.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:38:26.928+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:38:26.928+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:38:26.943+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:38:26.939+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1, in <module>
    from airflow import dag
ImportError: cannot import name 'dag' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2025-01-13T00:38:26.945+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:38:26.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.040 seconds
[2025-01-13T00:38:57.805+0000] {processor.py:186} INFO - Started process (PID=2177) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:38:57.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:38:57.808+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:38:57.808+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:38:57.822+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:38:57.819+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1, in <module>
    from airflow import dag
ImportError: cannot import name 'dag' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2025-01-13T00:38:57.824+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:38:57.841+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.040 seconds
[2025-01-13T00:39:28.838+0000] {processor.py:186} INFO - Started process (PID=2241) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:39:28.839+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:39:28.841+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:39:28.841+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:39:28.860+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:39:28.855+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1, in <module>
    from airflow import dag
ImportError: cannot import name 'dag' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2025-01-13T00:39:28.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:39:28.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.045 seconds
[2025-01-13T00:39:59.004+0000] {processor.py:186} INFO - Started process (PID=2305) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:39:59.005+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:39:59.007+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:39:59.006+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:39:59.021+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:39:59.017+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1, in <module>
    from airflow import dag
ImportError: cannot import name 'dag' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2025-01-13T00:39:59.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:39:59.040+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.041 seconds
[2025-01-13T00:40:29.254+0000] {processor.py:186} INFO - Started process (PID=2375) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:40:29.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:40:29.257+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:40:29.256+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:40:29.268+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:40:29.265+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1, in <module>
    from airflow import dag
ImportError: cannot import name 'dag' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2025-01-13T00:40:29.269+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:40:29.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.036 seconds
[2025-01-13T00:40:59.491+0000] {processor.py:186} INFO - Started process (PID=2439) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:40:59.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:40:59.494+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:40:59.494+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:40:59.521+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:40:59.512+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1, in <module>
    from airflow import dag
ImportError: cannot import name 'dag' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2025-01-13T00:40:59.523+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:40:59.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.051 seconds
[2025-01-13T00:41:29.610+0000] {processor.py:186} INFO - Started process (PID=2503) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:41:29.611+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:41:29.613+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:41:29.613+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:41:29.627+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:41:29.623+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1, in <module>
    from airflow import dag
ImportError: cannot import name 'dag' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2025-01-13T00:41:29.628+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:41:29.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.040 seconds
[2025-01-13T00:41:59.684+0000] {processor.py:186} INFO - Started process (PID=2567) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:41:59.685+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:41:59.687+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:41:59.687+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:41:59.706+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:41:59.702+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1, in <module>
    from airflow import dag
ImportError: cannot import name 'dag' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2025-01-13T00:41:59.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:41:59.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.051 seconds
[2025-01-13T00:42:29.871+0000] {processor.py:186} INFO - Started process (PID=2631) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:42:29.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:42:29.875+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:42:29.875+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:42:29.890+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:42:29.887+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1, in <module>
    from airflow import dag
ImportError: cannot import name 'dag' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2025-01-13T00:42:29.891+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:42:29.908+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.041 seconds
[2025-01-13T00:43:00.074+0000] {processor.py:186} INFO - Started process (PID=2695) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:43:00.075+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:43:00.079+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:43:00.078+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:43:00.114+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:43:00.106+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1, in <module>
    from airflow import dag
ImportError: cannot import name 'dag' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2025-01-13T00:43:00.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:43:00.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.070 seconds
[2025-01-13T00:43:30.229+0000] {processor.py:186} INFO - Started process (PID=2759) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:43:30.230+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:43:30.232+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:43:30.232+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:43:30.247+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:43:30.243+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1, in <module>
    from airflow import dag
ImportError: cannot import name 'dag' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2025-01-13T00:43:30.248+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:43:30.266+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.042 seconds
[2025-01-13T00:43:55.624+0000] {processor.py:186} INFO - Started process (PID=2817) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:43:55.625+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:43:55.627+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:43:55.627+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:43:55.657+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:43:55.652+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 9, in <module>
    from main import main_runner
ModuleNotFoundError: No module named 'main'
[2025-01-13T00:43:55.658+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:43:55.675+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.056 seconds
[2025-01-13T00:44:25.977+0000] {processor.py:186} INFO - Started process (PID=2881) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:44:25.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:44:25.980+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:44:25.980+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:44:25.995+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:44:25.992+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 9, in <module>
    from main import main_runner
ModuleNotFoundError: No module named 'main'
[2025-01-13T00:44:25.996+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:44:26.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.040 seconds
[2025-01-13T00:44:40.138+0000] {processor.py:186} INFO - Started process (PID=2888) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:44:40.139+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:44:40.141+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:44:40.141+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:44:40.166+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:44:40.163+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from main import main_runner
ModuleNotFoundError: No module named 'main'
[2025-01-13T00:44:40.167+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:44:40.181+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.046 seconds
[2025-01-13T00:45:10.437+0000] {processor.py:186} INFO - Started process (PID=2952) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:45:10.438+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:45:10.440+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:45:10.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:45:10.459+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:45:10.452+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from main import main_runner
ModuleNotFoundError: No module named 'main'
[2025-01-13T00:45:10.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:45:10.475+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.042 seconds
[2025-01-13T00:45:40.920+0000] {processor.py:186} INFO - Started process (PID=3016) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:45:40.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:45:40.923+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:45:40.922+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:45:40.936+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:45:40.933+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from main import main_runner
ModuleNotFoundError: No module named 'main'
[2025-01-13T00:45:40.937+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:45:40.951+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.036 seconds
[2025-01-13T00:46:11.472+0000] {processor.py:186} INFO - Started process (PID=3080) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:46:11.473+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:46:11.475+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:46:11.475+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:46:11.492+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:46:11.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from main import main_runner
ModuleNotFoundError: No module named 'main'
[2025-01-13T00:46:11.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:46:11.510+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.043 seconds
[2025-01-13T00:46:41.957+0000] {processor.py:186} INFO - Started process (PID=3144) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:46:41.957+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:46:41.960+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:46:41.959+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:46:41.978+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:46:41.975+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from main import main_runner
ModuleNotFoundError: No module named 'main'
[2025-01-13T00:46:41.980+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:46:41.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.043 seconds
[2025-01-13T00:47:12.154+0000] {processor.py:186} INFO - Started process (PID=3208) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:47:12.155+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:47:12.156+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:47:12.156+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:47:12.172+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:47:12.169+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from main import main_runner
ModuleNotFoundError: No module named 'main'
[2025-01-13T00:47:12.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:47:12.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.041 seconds
[2025-01-13T00:47:42.553+0000] {processor.py:186} INFO - Started process (PID=3272) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:47:42.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:47:42.556+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:47:42.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:47:42.574+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:47:42.570+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from main import main_runner
ModuleNotFoundError: No module named 'main'
[2025-01-13T00:47:42.576+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:47:42.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.048 seconds
[2025-01-13T00:48:09.710+0000] {processor.py:186} INFO - Started process (PID=3336) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:48:09.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:48:09.713+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:48:09.712+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:48:09.743+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:48:09.739+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    main = main_runner()
           ^^^^^^^^^^^
NameError: name 'main_runner' is not defined
[2025-01-13T00:48:09.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:48:09.763+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.057 seconds
[2025-01-13T00:48:27.361+0000] {processor.py:186} INFO - Started process (PID=3394) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:48:27.362+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:48:27.364+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:48:27.364+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:48:27.407+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:48:27.402+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 2, in <module>
    from main import main_runner
ModuleNotFoundError: No module named 'main'
[2025-01-13T00:48:27.409+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:48:27.425+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.069 seconds
[2025-01-13T00:48:58.298+0000] {processor.py:186} INFO - Started process (PID=3458) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:48:58.299+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:48:58.300+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:48:58.300+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:48:58.319+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:48:58.316+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 2, in <module>
    from main import main_runner
ModuleNotFoundError: No module named 'main'
[2025-01-13T00:48:58.320+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:48:58.336+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.043 seconds
[2025-01-13T00:49:29.251+0000] {processor.py:186} INFO - Started process (PID=3522) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:49:29.252+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:49:29.254+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:49:29.253+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:49:29.271+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:49:29.268+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 2, in <module>
    from main import main_runner
ModuleNotFoundError: No module named 'main'
[2025-01-13T00:49:29.272+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:49:29.288+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.041 seconds
[2025-01-13T00:49:59.949+0000] {processor.py:186} INFO - Started process (PID=3592) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:49:59.949+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:49:59.951+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:49:59.951+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:49:59.966+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:49:59.963+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 2, in <module>
    from main import main_runner
ModuleNotFoundError: No module named 'main'
[2025-01-13T00:49:59.968+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:49:59.984+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.040 seconds
[2025-01-13T00:50:30.810+0000] {processor.py:186} INFO - Started process (PID=3656) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:50:30.811+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:50:30.813+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:50:30.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:50:30.830+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:50:30.825+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 2, in <module>
    from main import main_runner
ModuleNotFoundError: No module named 'main'
[2025-01-13T00:50:30.831+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:50:30.846+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.040 seconds
[2025-01-13T00:50:44.975+0000] {processor.py:186} INFO - Started process (PID=3657) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:50:44.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:50:44.978+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:50:44.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:50:45.010+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:50:45.006+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 2, in <module>
    from ufc_backend_scraper.main import main_runner
ModuleNotFoundError: No module named 'ufc_backend_scraper'
[2025-01-13T00:50:45.011+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:50:45.029+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.059 seconds
[2025-01-13T00:51:15.877+0000] {processor.py:186} INFO - Started process (PID=3721) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:51:15.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:51:15.880+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:51:15.880+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:51:15.900+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:51:15.895+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 2, in <module>
    from ufc_backend_scraper.main import main_runner
ModuleNotFoundError: No module named 'ufc_backend_scraper'
[2025-01-13T00:51:15.901+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:51:15.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.048 seconds
[2025-01-13T00:51:46.611+0000] {processor.py:186} INFO - Started process (PID=3785) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:51:46.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:51:46.614+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:51:46.614+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:51:46.629+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:51:46.626+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 2, in <module>
    from ufc_backend_scraper.main import main_runner
ModuleNotFoundError: No module named 'ufc_backend_scraper'
[2025-01-13T00:51:46.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:51:46.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.041 seconds
[2025-01-13T00:52:17.685+0000] {processor.py:186} INFO - Started process (PID=3849) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:52:17.686+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:52:17.688+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:52:17.688+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:52:17.716+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:52:17.709+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 2, in <module>
    from ufc_backend_scraper.main import main_runner
ModuleNotFoundError: No module named 'ufc_backend_scraper'
[2025-01-13T00:52:17.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:52:17.734+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.052 seconds
[2025-01-13T00:52:33.345+0000] {processor.py:186} INFO - Started process (PID=3913) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:52:33.346+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:52:33.348+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:52:33.348+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:52:33.386+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:52:33.382+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from dags.ufc_etl.main import main_runner
ModuleNotFoundError: No module named 'dags'
[2025-01-13T00:52:33.387+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:52:33.403+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.063 seconds
[2025-01-13T00:52:56.562+0000] {processor.py:186} INFO - Started process (PID=3914) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:52:56.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:52:56.565+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:52:56.564+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:52:56.663+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:52:56.656+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from ufc_etl.main import main_runner
  File "/opt/airflow/dags/ufc_etl/main.py", line 1, in <module>
    from utils.db_connec import connect_to_database
ModuleNotFoundError: No module named 'utils'
[2025-01-13T00:52:56.666+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:52:56.682+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.125 seconds
[2025-01-13T00:53:27.524+0000] {processor.py:186} INFO - Started process (PID=3978) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:53:27.525+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:53:27.528+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:53:27.527+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:53:27.625+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:53:27.614+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from ufc_etl.main import main_runner
  File "/opt/airflow/dags/ufc_etl/main.py", line 1, in <module>
    from utils.db_connec import connect_to_database
ModuleNotFoundError: No module named 'utils'
[2025-01-13T00:53:27.629+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:53:27.650+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.130 seconds
[2025-01-13T00:53:57.724+0000] {processor.py:186} INFO - Started process (PID=4042) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:53:57.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:53:57.729+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:53:57.728+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:53:57.804+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:53:57.796+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from ufc_etl.main import main_runner
  File "/opt/airflow/dags/ufc_etl/main.py", line 1, in <module>
    from utils.db_connec import connect_to_database
ModuleNotFoundError: No module named 'utils'
[2025-01-13T00:53:57.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:53:57.833+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.114 seconds
[2025-01-13T00:54:28.717+0000] {processor.py:186} INFO - Started process (PID=4106) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:54:28.718+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:54:28.720+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:54:28.720+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:54:28.769+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:54:28.760+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from ufc_etl.main import main_runner
  File "/opt/airflow/dags/ufc_etl/main.py", line 1, in <module>
    from utils.db_connec import connect_to_database
ModuleNotFoundError: No module named 'utils'
[2025-01-13T00:54:28.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:54:28.788+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.075 seconds
[2025-01-13T00:54:59.559+0000] {processor.py:186} INFO - Started process (PID=4170) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:54:59.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:54:59.562+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:54:59.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:54:59.599+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:54:59.592+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from ufc_etl.main import main_runner
  File "/opt/airflow/dags/ufc_etl/main.py", line 1, in <module>
    from utils.db_connec import connect_to_database
ModuleNotFoundError: No module named 'utils'
[2025-01-13T00:54:59.602+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:54:59.618+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.064 seconds
[2025-01-13T00:55:30.656+0000] {processor.py:186} INFO - Started process (PID=4240) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:55:30.657+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:55:30.659+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:55:30.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:55:30.706+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:55:30.698+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from ufc_etl.main import main_runner
  File "/opt/airflow/dags/ufc_etl/main.py", line 1, in <module>
    from utils.db_connec import connect_to_database
ModuleNotFoundError: No module named 'utils'
[2025-01-13T00:55:30.709+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:55:30.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.077 seconds
[2025-01-13T00:56:00.841+0000] {processor.py:186} INFO - Started process (PID=4304) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:56:00.842+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:56:00.844+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:56:00.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:56:00.884+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:56:00.877+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from ufc_etl.main import main_runner
  File "/opt/airflow/dags/ufc_etl/main.py", line 1, in <module>
    from utils.db_connec import connect_to_database
ModuleNotFoundError: No module named 'utils'
[2025-01-13T00:56:00.886+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:56:00.903+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.066 seconds
[2025-01-13T00:56:30.964+0000] {processor.py:186} INFO - Started process (PID=4367) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:56:30.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:56:30.967+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:56:30.966+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:56:31.035+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:56:31.009+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from ufc_etl.main import main_runner
  File "/opt/airflow/dags/ufc_etl/main.py", line 1, in <module>
    from utils.db_connec import connect_to_database
ModuleNotFoundError: No module named 'utils'
[2025-01-13T00:56:31.046+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:56:31.064+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.104 seconds
[2025-01-13T00:57:01.456+0000] {processor.py:186} INFO - Started process (PID=4431) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:57:01.457+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:57:01.459+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:57:01.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:57:01.490+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:57:01.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from ufc_etl.main import main_runner
  File "/opt/airflow/dags/ufc_etl/main.py", line 1, in <module>
    from utils.db_connec import connect_to_database
ModuleNotFoundError: No module named 'utils'
[2025-01-13T00:57:01.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:57:01.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.057 seconds
[2025-01-13T00:57:32.332+0000] {processor.py:186} INFO - Started process (PID=4495) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:57:32.333+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:57:32.335+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:57:32.335+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:57:32.444+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:57:32.437+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from ufc_etl.main import main_runner
  File "/opt/airflow/dags/ufc_etl/main.py", line 2, in <module>
    from utils.extract import getEventsWhichIsNotInDatabase, getFightDetails, getFighterDetails
ModuleNotFoundError: No module named 'utils'
[2025-01-13T00:57:32.448+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:57:32.464+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.137 seconds
[2025-01-13T00:58:02.576+0000] {processor.py:186} INFO - Started process (PID=4559) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:58:02.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:58:02.579+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:58:02.579+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:58:02.829+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:58:02.821+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from ufc_etl.main import main_runner
  File "/opt/airflow/dags/ufc_etl/main.py", line 3, in <module>
    from ufc_etl.utils.load import add_data_to_database, add_non_added_fighters_to_database, aggregated_data_to_database
  File "/opt/airflow/dags/ufc_etl/utils/load.py", line 4, in <module>
    from utils.load_utils.load_utils_funcs import getCorrectAggregatedData
ModuleNotFoundError: No module named 'utils'
[2025-01-13T00:58:02.834+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:58:02.848+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.277 seconds
[2025-01-13T00:58:32.944+0000] {processor.py:186} INFO - Started process (PID=4624) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:58:32.945+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:58:32.947+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:58:32.946+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:58:33.243+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:58:33.228+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from ufc_etl.main import main_runner
  File "/opt/airflow/dags/ufc_etl/main.py", line 3, in <module>
    from ufc_etl.utils.load import add_data_to_database, add_non_added_fighters_to_database, aggregated_data_to_database
  File "/opt/airflow/dags/ufc_etl/utils/load.py", line 5, in <module>
    from ufc_etl.utils.transform import add_extra_aggregate_data_to_db
  File "/opt/airflow/dags/ufc_etl/utils/transform.py", line 3, in <module>
    from utils.transform_utils.aggregate_utility_funcs import add_to_aggregation_array, average_time_taken_per_fight, avg_succesful_clinches_per_fight, calculate_sig_strikes_body_part_percent, finishing_rate, total_sig_strikes_pff
ModuleNotFoundError: No module named 'utils'
[2025-01-13T00:58:33.247+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:58:33.261+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.321 seconds
[2025-01-13T00:59:03.736+0000] {processor.py:186} INFO - Started process (PID=4687) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:59:03.737+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:59:03.739+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:59:03.739+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:59:04.068+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:59:04.033+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from ufc_etl.main import main_runner
  File "/opt/airflow/dags/ufc_etl/main.py", line 3, in <module>
    from ufc_etl.utils.load import add_data_to_database, add_non_added_fighters_to_database, aggregated_data_to_database
  File "/opt/airflow/dags/ufc_etl/utils/load.py", line 5, in <module>
    from ufc_etl.utils.transform import add_extra_aggregate_data_to_db
  File "/opt/airflow/dags/ufc_etl/utils/transform.py", line 3, in <module>
    from ufc_etl.utils.transform_utils.aggregate_utility_funcs import add_to_aggregation_array, average_time_taken_per_fight, avg_succesful_clinches_per_fight, calculate_sig_strikes_body_part_percent, finishing_rate, total_sig_strikes_pff
  File "/opt/airflow/dags/ufc_etl/utils/transform_utils/aggregate_utility_funcs.py", line 2, in <module>
    from utils.transform_utils.transform_utility_funcs import extract_landed_strikes, time_to_timedelta
ModuleNotFoundError: No module named 'utils'
[2025-01-13T00:59:04.075+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:59:04.091+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.360 seconds
[2025-01-13T00:59:34.260+0000] {processor.py:186} INFO - Started process (PID=4751) to work on /opt/airflow/dags/dag.py
[2025-01-13T00:59:34.261+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T00:59:34.263+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:59:34.263+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T00:59:34.945+0000] {logging_mixin.py:190} INFO - Connection successful!
[2025-01-13T00:59:35.943+0000] {logging_mixin.py:190} INFO - No fights available and No events available
[2025-01-13T00:59:35.965+0000] {logging_mixin.py:190} INFO - No fights available
[2025-01-13T00:59:36.169+0000] {logging_mixin.py:190} INFO - Connection successful!
[2025-01-13T00:59:36.170+0000] {logging_mixin.py:190} INFO - Could not get the fighter data
[2025-01-13T00:59:36.172+0000] {logging_mixin.py:190} INFO - No data to be added to the database
[2025-01-13T00:59:36.180+0000] {logging_mixin.py:190} INFO - [2025-01-13T00:59:36.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22, in <module>
    run_etl = PythonOperator(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-01-13T00:59:36.180+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T00:59:36.198+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 1.942 seconds
[2025-01-13T01:00:06.238+0000] {processor.py:186} INFO - Started process (PID=4823) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:00:06.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:00:06.241+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:00:06.241+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:00:06.776+0000] {logging_mixin.py:190} INFO - Connection successful!
[2025-01-13T01:00:07.544+0000] {logging_mixin.py:190} INFO - No fights available and No events available
[2025-01-13T01:00:07.567+0000] {logging_mixin.py:190} INFO - No fights available
[2025-01-13T01:00:07.751+0000] {logging_mixin.py:190} INFO - Connection successful!
[2025-01-13T01:00:07.752+0000] {logging_mixin.py:190} INFO - Could not get the fighter data
[2025-01-13T01:00:07.753+0000] {logging_mixin.py:190} INFO - No data to be added to the database
[2025-01-13T01:00:07.760+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:00:07.756+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22, in <module>
    run_etl = PythonOperator(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-01-13T01:00:07.761+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:00:07.778+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 1.545 seconds
[2025-01-13T01:00:38.678+0000] {processor.py:186} INFO - Started process (PID=4892) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:00:38.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:00:38.680+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:00:38.680+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:00:39.215+0000] {logging_mixin.py:190} INFO - Connection successful!
[2025-01-13T01:00:40.293+0000] {logging_mixin.py:190} INFO - No fights available and No events available
[2025-01-13T01:00:40.314+0000] {logging_mixin.py:190} INFO - No fights available
[2025-01-13T01:00:40.517+0000] {logging_mixin.py:190} INFO - Connection successful!
[2025-01-13T01:00:40.518+0000] {logging_mixin.py:190} INFO - Could not get the fighter data
[2025-01-13T01:00:40.520+0000] {logging_mixin.py:190} INFO - No data to be added to the database
[2025-01-13T01:00:40.528+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:00:40.523+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22, in <module>
    run_etl = PythonOperator(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-01-13T01:00:40.529+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:00:40.546+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 1.873 seconds
[2025-01-13T01:01:10.672+0000] {processor.py:186} INFO - Started process (PID=4962) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:01:10.673+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:01:10.674+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:01:10.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:01:11.247+0000] {logging_mixin.py:190} INFO - Connection successful!
[2025-01-13T01:01:11.949+0000] {logging_mixin.py:190} INFO - No fights available and No events available
[2025-01-13T01:01:11.969+0000] {logging_mixin.py:190} INFO - No fights available
[2025-01-13T01:01:12.153+0000] {logging_mixin.py:190} INFO - Connection successful!
[2025-01-13T01:01:12.154+0000] {logging_mixin.py:190} INFO - Could not get the fighter data
[2025-01-13T01:01:12.157+0000] {logging_mixin.py:190} INFO - No data to be added to the database
[2025-01-13T01:01:12.168+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:01:12.161+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22, in <module>
    run_etl = PythonOperator(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-01-13T01:01:12.169+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:01:12.186+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 1.519 seconds
[2025-01-13T01:01:42.780+0000] {processor.py:186} INFO - Started process (PID=5027) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:01:42.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:01:42.784+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:01:42.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:01:43.362+0000] {logging_mixin.py:190} INFO - Connection successful!
[2025-01-13T01:01:44.364+0000] {logging_mixin.py:190} INFO - No fights available and No events available
[2025-01-13T01:01:44.385+0000] {logging_mixin.py:190} INFO - No fights available
[2025-01-13T01:01:44.561+0000] {logging_mixin.py:190} INFO - Connection successful!
[2025-01-13T01:01:44.562+0000] {logging_mixin.py:190} INFO - Could not get the fighter data
[2025-01-13T01:01:44.563+0000] {logging_mixin.py:190} INFO - No data to be added to the database
[2025-01-13T01:01:44.588+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:01:44.567+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22, in <module>
    task_id = 'run_etl_script',
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-01-13T01:01:44.589+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:01:44.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 1.831 seconds
[2025-01-13T01:02:14.714+0000] {processor.py:186} INFO - Started process (PID=5095) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:02:14.716+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:02:14.718+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:02:14.718+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:02:14.963+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:02:15.046+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:02:15.046+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:weekly_ufc_dag
[2025-01-13T01:02:15.057+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:02:15.057+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:weekly_ufc_dag
[2025-01-13T01:02:15.064+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:02:15.064+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:weekly_ufc_dag
[2025-01-13T01:02:15.073+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:02:15.073+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:weekly_ufc_dag
[2025-01-13T01:02:15.080+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:02:15.080+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:weekly_ufc_dag
[2025-01-13T01:02:15.087+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:02:15.087+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:weekly_ufc_dag
[2025-01-13T01:02:15.094+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:02:15.094+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:weekly_ufc_dag
[2025-01-13T01:02:15.095+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:02:15.094+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:02:15.104+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:02:15.104+0000] {dag.py:3262} INFO - Creating ORM DAG for weekly_ufc_dag
[2025-01-13T01:02:15.113+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:02:15.112+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:02:15.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.419 seconds
[2025-01-13T01:02:46.045+0000] {processor.py:186} INFO - Started process (PID=5158) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:02:46.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:02:46.048+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:02:46.048+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:02:46.305+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:02:46.322+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:02:46.322+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:02:46.343+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:02:46.343+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:02:46.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.322 seconds
[2025-01-13T01:03:16.436+0000] {processor.py:186} INFO - Started process (PID=5223) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:03:16.437+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:03:16.438+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:03:16.438+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:03:16.659+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:03:16.673+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:03:16.672+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:03:16.693+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:03:16.693+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:03:16.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.283 seconds
[2025-01-13T01:03:46.941+0000] {processor.py:186} INFO - Started process (PID=5287) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:03:46.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:03:46.945+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:03:46.945+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:03:47.234+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:03:47.248+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:03:47.247+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:03:47.265+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:03:47.265+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:03:47.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.345 seconds
[2025-01-13T01:04:17.336+0000] {processor.py:186} INFO - Started process (PID=5353) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:04:17.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:04:17.339+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:04:17.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:04:17.604+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:04:17.619+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:04:17.619+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:04:17.636+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:04:17.636+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:04:17.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.323 seconds
[2025-01-13T01:04:47.759+0000] {processor.py:186} INFO - Started process (PID=5418) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:04:47.760+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:04:47.762+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:04:47.762+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:04:48.052+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:04:48.066+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:04:48.066+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:04:48.083+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:04:48.083+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:04:48.100+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.346 seconds
[2025-01-13T01:05:18.899+0000] {processor.py:186} INFO - Started process (PID=5482) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:05:18.900+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:05:18.901+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:05:18.901+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:05:19.105+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:05:19.119+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:05:19.119+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:05:19.134+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:05:19.134+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:05:19.154+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.259 seconds
[2025-01-13T01:05:49.238+0000] {processor.py:186} INFO - Started process (PID=5546) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:05:49.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:05:49.241+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:05:49.241+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:05:49.444+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:05:49.458+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:05:49.458+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:05:49.474+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:05:49.474+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:05:49.488+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.255 seconds
[2025-01-13T01:06:20.374+0000] {processor.py:186} INFO - Started process (PID=5610) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:06:20.375+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:06:20.377+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:06:20.376+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:06:20.662+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:06:20.678+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:06:20.677+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:06:20.696+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:06:20.696+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:06:20.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.346 seconds
[2025-01-13T01:06:50.786+0000] {processor.py:186} INFO - Started process (PID=5674) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:06:50.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:06:50.789+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:06:50.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:06:51.114+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:06:51.128+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:06:51.127+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:06:51.143+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:06:51.142+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:06:51.162+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.380 seconds
[2025-01-13T01:07:21.990+0000] {processor.py:186} INFO - Started process (PID=5738) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:07:21.992+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:07:21.994+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:07:21.994+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:07:22.235+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:07:22.249+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:07:22.249+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:07:22.265+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:07:22.265+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:07:22.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.295 seconds
[2025-01-13T01:07:52.431+0000] {processor.py:186} INFO - Started process (PID=5805) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:07:52.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:07:52.434+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:07:52.434+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:07:52.722+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:07:52.737+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:07:52.737+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:07:52.755+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:07:52.754+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:07:52.773+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.347 seconds
[2025-01-13T01:08:22.884+0000] {processor.py:186} INFO - Started process (PID=5870) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:08:22.885+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:08:22.887+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:08:22.887+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:08:23.163+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:08:23.178+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:08:23.178+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:08:23.195+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:08:23.195+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:08:23.212+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.333 seconds
[2025-01-13T01:08:53.389+0000] {processor.py:186} INFO - Started process (PID=5935) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:08:53.391+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:08:53.393+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:08:53.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:08:53.683+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:08:53.698+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:08:53.697+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:08:53.714+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:08:53.713+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:08:53.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.348 seconds
[2025-01-13T01:09:23.818+0000] {processor.py:186} INFO - Started process (PID=5999) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:09:23.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:09:23.821+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:09:23.821+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:09:24.060+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:09:24.075+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:09:24.074+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:09:24.093+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:09:24.093+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:09:24.110+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.296 seconds
[2025-01-13T01:09:54.313+0000] {processor.py:186} INFO - Started process (PID=6063) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:09:54.314+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:09:54.316+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:09:54.316+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:09:54.559+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:09:54.574+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:09:54.573+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:09:54.590+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:09:54.589+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:09:54.605+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.297 seconds
[2025-01-13T01:10:24.916+0000] {processor.py:186} INFO - Started process (PID=6122) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:10:24.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:10:24.918+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:10:24.918+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:10:25.186+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:10:25.201+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:10:25.201+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:10:25.220+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:10:25.219+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:10:25.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.328 seconds
[2025-01-13T01:10:55.388+0000] {processor.py:186} INFO - Started process (PID=6189) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:10:55.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:10:55.391+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:10:55.390+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:10:55.705+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:10:55.718+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:10:55.717+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:10:55.733+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:10:55.733+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:10:55.751+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.368 seconds
[2025-01-13T01:11:26.669+0000] {processor.py:186} INFO - Started process (PID=6255) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:11:26.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:11:26.672+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:11:26.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:11:26.884+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:11:26.896+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:11:26.895+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:11:26.912+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:11:26.912+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:11:26.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.266 seconds
[2025-01-13T01:11:57.264+0000] {processor.py:186} INFO - Started process (PID=6319) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:11:57.265+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:11:57.267+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:11:57.267+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:11:57.585+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:11:57.597+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:11:57.597+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:11:57.612+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:11:57.612+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:11:57.627+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.367 seconds
[2025-01-13T01:12:27.936+0000] {processor.py:186} INFO - Started process (PID=6383) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:12:27.937+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:12:27.939+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:12:27.939+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:12:28.189+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:12:28.204+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:12:28.204+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:12:28.227+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:12:28.227+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:12:28.248+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.317 seconds
[2025-01-13T01:12:59.117+0000] {processor.py:186} INFO - Started process (PID=6447) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:12:59.118+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:12:59.120+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:12:59.120+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:12:59.407+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:12:59.423+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:12:59.422+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:12:59.441+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:12:59.441+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:12:59.460+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.348 seconds
[2025-01-13T01:13:29.521+0000] {processor.py:186} INFO - Started process (PID=6511) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:13:29.521+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:13:29.523+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:13:29.523+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:13:29.755+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:13:29.769+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:13:29.768+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:13:29.784+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:13:29.784+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:13:29.806+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.289 seconds
[2025-01-13T01:14:00.295+0000] {processor.py:186} INFO - Started process (PID=6575) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:14:00.297+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:14:00.299+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:14:00.299+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:14:00.570+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:14:00.591+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:14:00.590+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:14:00.616+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:14:00.616+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:14:00.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.353 seconds
[2025-01-13T01:14:30.727+0000] {processor.py:186} INFO - Started process (PID=6639) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:14:30.728+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:14:30.730+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:14:30.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:14:30.980+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:14:30.993+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:14:30.992+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:14:31.008+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:14:31.008+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:14:31.029+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.306 seconds
[2025-01-13T01:15:01.093+0000] {processor.py:186} INFO - Started process (PID=6708) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:15:01.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:15:01.097+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:15:01.097+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:15:01.415+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:15:01.430+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:15:01.430+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:15:01.446+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:15:01.446+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:15:01.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.377 seconds
[2025-01-13T01:15:31.693+0000] {processor.py:186} INFO - Started process (PID=6772) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:15:31.694+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:15:31.697+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:15:31.697+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:15:31.952+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:15:31.967+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:15:31.967+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:15:31.983+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:15:31.982+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:15:31.998+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.309 seconds
[2025-01-13T01:16:02.347+0000] {processor.py:186} INFO - Started process (PID=6836) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:16:02.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:16:02.351+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:16:02.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:16:02.620+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:16:02.635+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:16:02.635+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:16:02.655+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:16:02.655+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:16:02.673+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.330 seconds
[2025-01-13T01:16:33.023+0000] {processor.py:186} INFO - Started process (PID=6900) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:16:33.024+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:16:33.026+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:16:33.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:16:33.340+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:16:33.356+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:16:33.356+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:16:33.378+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:16:33.378+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:16:33.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.381 seconds
[2025-01-13T01:17:03.961+0000] {processor.py:186} INFO - Started process (PID=6964) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:17:03.962+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:17:03.965+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:17:03.964+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:17:04.255+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:17:04.271+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:17:04.270+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:17:04.290+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:17:04.289+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:17:04.307+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.352 seconds
[2025-01-13T01:17:34.747+0000] {processor.py:186} INFO - Started process (PID=7028) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:17:34.748+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:17:34.750+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:17:34.750+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:17:35.098+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:17:35.113+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:17:35.113+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:17:35.130+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:17:35.130+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:17:35.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.405 seconds
[2025-01-13T01:18:06.001+0000] {processor.py:186} INFO - Started process (PID=7092) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:18:06.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:18:06.004+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:18:06.004+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:18:06.304+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:18:06.317+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:18:06.317+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:18:06.334+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:18:06.334+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:18:06.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.359 seconds
[2025-01-13T01:18:36.602+0000] {processor.py:186} INFO - Started process (PID=7156) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:18:36.603+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:18:36.606+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:18:36.605+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:18:36.848+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:18:36.861+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:18:36.860+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:18:36.876+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:18:36.875+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:18:36.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.296 seconds
[2025-01-13T01:19:06.980+0000] {processor.py:186} INFO - Started process (PID=7220) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:19:06.981+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:19:06.983+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:19:06.982+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:19:07.255+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:19:07.271+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:19:07.271+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:19:07.289+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:19:07.288+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:19:07.305+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.330 seconds
[2025-01-13T01:19:37.738+0000] {processor.py:186} INFO - Started process (PID=7284) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:19:37.739+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:19:37.741+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:19:37.741+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:19:38.004+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:19:38.021+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:19:38.020+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:19:38.042+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:19:38.042+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:19:38.063+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.330 seconds
[2025-01-13T01:20:08.892+0000] {processor.py:186} INFO - Started process (PID=7348) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:20:08.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:20:08.895+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:20:08.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:20:09.152+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:20:09.165+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:20:09.165+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:20:09.181+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:20:09.181+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:20:09.200+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.312 seconds
[2025-01-13T01:20:39.734+0000] {processor.py:186} INFO - Started process (PID=7411) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:20:39.735+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:20:39.737+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:20:39.737+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:20:39.985+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:20:40.000+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:20:40.000+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:20:40.018+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:20:40.017+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:20:40.039+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.309 seconds
[2025-01-13T01:21:10.365+0000] {processor.py:186} INFO - Started process (PID=7475) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:21:10.366+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:21:10.369+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:21:10.369+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:21:10.665+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:21:10.678+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:21:10.677+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:21:10.692+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:21:10.692+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-05 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-13T01:21:10.709+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.348 seconds
[2025-01-13T01:29:47.583+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:29:47.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:29:47.586+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:29:47.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:29:47.934+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:29:47.952+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:29:47.952+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:29:47.973+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:29:47.973+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-12 00:00:00+00:00, run_after=2025-01-19 00:00:00+00:00
[2025-01-13T01:29:47.992+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.414 seconds
[2025-01-13T01:30:18.079+0000] {processor.py:186} INFO - Started process (PID=145) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:30:18.080+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:30:18.082+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:30:18.082+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:30:18.321+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:30:18.334+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:30:18.333+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:30:18.351+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:30:18.351+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-12 00:00:00+00:00, run_after=2025-01-19 00:00:00+00:00
[2025-01-13T01:30:18.369+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.294 seconds
[2025-01-13T01:30:48.408+0000] {processor.py:186} INFO - Started process (PID=211) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:30:48.409+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:30:48.411+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:30:48.411+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:30:48.692+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:30:48.705+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:30:48.705+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:30:48.721+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:30:48.721+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-12 00:00:00+00:00, run_after=2025-01-19 00:00:00+00:00
[2025-01-13T01:30:48.742+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.339 seconds
[2025-01-13T01:31:18.798+0000] {processor.py:186} INFO - Started process (PID=275) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:31:18.800+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:31:18.802+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:31:18.802+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:31:19.025+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:31:19.040+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:31:19.040+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:31:19.057+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:31:19.057+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-12 00:00:00+00:00, run_after=2025-01-19 00:00:00+00:00
[2025-01-13T01:31:19.080+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.286 seconds
[2025-01-13T01:31:50.029+0000] {processor.py:186} INFO - Started process (PID=339) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:31:50.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:31:50.032+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:31:50.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:31:50.299+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:31:50.316+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:31:50.315+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:31:50.337+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:31:50.337+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-12 00:00:00+00:00, run_after=2025-01-19 00:00:00+00:00
[2025-01-13T01:31:50.355+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.330 seconds
[2025-01-13T01:32:20.553+0000] {processor.py:186} INFO - Started process (PID=403) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:32:20.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:32:20.556+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:32:20.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:32:20.876+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:32:20.890+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:32:20.890+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:32:20.907+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:32:20.907+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-12 00:00:00+00:00, run_after=2025-01-19 00:00:00+00:00
[2025-01-13T01:32:20.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.375 seconds
[2025-01-13T01:32:51.088+0000] {processor.py:186} INFO - Started process (PID=470) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:32:51.089+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:32:51.091+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:32:51.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:32:51.412+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:32:51.426+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:32:51.425+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:32:51.442+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:32:51.442+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-12 00:00:00+00:00, run_after=2025-01-19 00:00:00+00:00
[2025-01-13T01:32:51.462+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.379 seconds
[2025-01-13T01:33:21.596+0000] {processor.py:186} INFO - Started process (PID=537) to work on /opt/airflow/dags/dag.py
[2025-01-13T01:33:21.597+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-13T01:33:21.600+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:33:21.599+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-13T01:33:21.837+0000] {processor.py:925} INFO - DAG(s) 'weekly_ufc_dag' retrieved from /opt/airflow/dags/dag.py
[2025-01-13T01:33:21.850+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:33:21.850+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T01:33:21.867+0000] {logging_mixin.py:190} INFO - [2025-01-13T01:33:21.867+0000] {dag.py:4180} INFO - Setting next_dagrun for weekly_ufc_dag to 2025-01-12 00:00:00+00:00, run_after=2025-01-19 00:00:00+00:00
[2025-01-13T01:33:21.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.292 seconds
